// Crewmate-videos snapshot @ 2024-08-25
const crewmateIdsWithVideoDefault = [
    1477, // [1ST] Deryck Goldfinger | BIgE92
    1663, // [1ST] Deryck Goldfinger | BIgE92
    2426, // Elerium115
    2428, // Elerium115
    3547, // [1ST] Skippy The Magnificent
    5097, // [1ST] Skippy The Magnificent
    5807, // [1ST] Skippy The Magnificent
    7383, // [1ST] Deryck Goldfinger | BIgE92
    20193, // Elerium115
    20457, // [1ST] Deryck Goldfinger | BIgE92
    26207, // [1ST] Deryck Goldfinger | BIgE92
    27392, // Elerium115
    27395, // Elerium115
    29933, // Elerium115
    35933, // Elerium115
];

const crewmateVideosBaseUrl = 'https://influence.elerium.dev/assets/crewmate-videos';
const crewmateVideosDefault = {};
crewmateIdsWithVideoDefault.forEach(crewmateId => {
    crewmateVideosDefault[crewmateId] = `${crewmateVideosBaseUrl}/${crewmateId}.mp4`;
});

// Prices snapshot @ 2024-08-25
const pricesDefault = {
    "Acetylene": 0.0245,
    "Acrylonitrile": 0.15838,
    "Alumina": 2,
    "Alumina Ceramic": 2.5,
    "Aluminium": 4.5,
    "Aluminium Beam": 5,
    "Aluminium Hull Plate": 2750,
    "Aluminium Pipe": 5,
    "Aluminium Sheet": 4.5,
    "Aluminium Truss": 10000,
    "Ammonia": 0.115635,
    "Ammonium Carbonate": 0.099,
    "Ammonium Chloride": 0.89,
    "Ammonium Diuranate": 0.096407,
    "Ammonium Oxalate": 0.054099,
    "Ammonium Paratungstate": 0.62352,
    "Apatite": 0.00005,
    "Attitude Control Module": 7900,
    "Austenitic Nichrome": 2.5,
    "Avionics Module": 5000,
    "Ball Bearing": 0.5,
    "Ball Valve": 5,
    "Bare Circuit Board": 90,
    "Bare Copper Wire": 0.48,
    "Beryllia": 21.0335,
    "Beryllia Ceramic": 8.4,
    "Beryllium Carbonate": 4.883592819653332,
    "Bioreactor": 149973,
    "Bisphenol A": 1.18,
    "Bitumen": 0.0005,
    "Borax": 0.05,
    "Boria": 1.30935,
    "Boric Acid": 1.1,
    "Boron": 1.9,
    "Borosilicate Glass": 3.69,
    "Brushless Motor": 19,
    "Brushless Motor Rotor": 5.84545,
    "Brushless Motor Stator": 6.39223,
    "CCD": 3000,
    "Calcite": 0.0004,
    "Calcium": 0.099,
    "Calcium Chloride": 0.139,
    "Carbon Dioxide": 0.0003,
    "Carbon Fiber": 0.45,
    "Carbon Monoxide": 0.00001,
    "Cargo Module": 20881.25,
    "Cargo Ring": 49999,
    "Cement": 0.003,
    "Chlorine": 0.05238663484486873,
    "Chromia": 0.845861,
    "Chromium": 6,
    "Circuit Board": 125,
    "Closed-cycle Gas Core Nuclear Reactor Engine": 200000,
    "Coffinite": 0.02826,
    "Cold Gas Thruster": 15,
    "Cold Gas Torque Thruster": 15,
    "Composite-overwrapped Reactor Shell": 3166.3,
    "Computer": 710,
    "Computer Chip": 7899,
    "Control Moment Gyroscope": 687.23,
    "Copper": 0.19,
    "Copper Wire": 0.19,
    "Core Drill": 60,
    "Core Drill Bit": 0.205829,
    "Core Drill Thruster": 44.7188,
    "Deionized Water": 0.0018,
    "Diepoxy Prepolymer Resin": 0.694767,
    "Diode": 8.5,
    "Engine Bell": 8738.095238095239,
    "Epichlorohydrin": 4,
    "Epoxy": 1.55,
    "Escape Module": 50069,
    "Extractor": 30215.1,
    "Factory": 185442,
    "Feldspar": 0.115,
    "Ferrite": 0.4,
    "Ferrite-bead Inductor": 0.817122,
    "Ferrochromium": 0.35,
    "Ferromolybdenum": 0.3,
    "Ferrosilicon": 0.46003,
    "Fiber Optic Cable": 0.485,
    "Fiber Optic Gyroscope": 4.63926,
    "Fiberglass": 0.2,
    "Flow Divider Moderator": 95000,
    "Fluids Automation Module": 7000,
    "Fluorine": 9.99,
    "Food": 0.33,
    "Fuel Make-up Tank": 26333.333333333332,
    "Fused Quartz": 0.1859,
    "Fused Quartz Lightbulb Tube": 63.8284,
    "Gold": 19999,
    "Graphite": 0.28,
    "Habitat": 3278250,
    "Habitation Module": 10300,
    "Heat Exchanger": 33.6247,
    "Heavy Transport": 4553100,
    "Heavy Transport Hull": 2500000,
    "Highly Enriched Uranium Hexafluoride": 490.602,
    "Highly Enriched Uranium Powder": 975,
    "Hydrochloric Acid": 0.079,
    "Hydrofluoric Acid": 5.89,
    "Hydrogen": 0.029,
    "Hydrogen Heptafluorotantalate and Niobate": 4.01025,
    "Hydrogen Propellant": 0.0535,
    "Iron": 0.119,
    "Iron Oxide": 0.224421,
    "Iron Sulfide": 0.082038,
    "Landing Auger": 52.5254,
    "Landing Leg": 131.001,
    "Large Thrust Bearing": 438,
    "Laser Diode": 51.469,
    "Leached Coffinite": 0.239956,
    "Leached Feldspar": 2,
    "Lead": 4.99,
    "Lead Sulfide": 0.820382,
    "LiPo Battery": 12.5,
    "Light Transport": 850622,
    "Light Transport Hull": 585222,
    "Lightbulb End Moderators": 1614.09,
    "Lithium": 0.38,
    "Lithium Carbonate": 0.02,
    "Lithium Chloride": 0.25,
    "Lithium Sulfate": 0.015,
    "Magnesia": 0.5,
    "Magnesium": 0.85,
    "Magnesium Chloride": 0.022,
    "Marketplace": 1272920,
    "Merrillite": 0.091362,
    "Methane": 0.0036,
    "Mobility Module": 20000,
    "Molybdenum Disulfide": 1.31261,
    "Molybdenum Trioxide": 3,
    "Naphtha": 0.0388,
    "Natural Flavorings": 5,
    "Nd:YAG Laser": 50,
    "Nd:YAG Laser Rod": 1.72803,
    "Neodymium": 2.35899,
    "Neodymium Magnet": 4,
    "Neodymium Oxide": 25,
    "Neodymium Trichloride": 1.23512,
    "Neon": 20,
    "Neon Make-up Tank": 820.187,
    "Neon/Fuel Separator Centrifuge": 1136.91,
    "Nichrome": 4.5,
    "Nickel": 0.049,
    "Nickel Oxide": 2.07056,
    "Nitric Acid": 0.047,
    "Nitrogen": 0.18,
    "Novolak Prepolymer Resin": 0.88,
    "Nuclear Lightbulb": 7690,
    "Olivine": 0.057645,
    "Oxalic Acid": 0.041177,
    "Oxygen": 0.0195,
    "PEDOT": 16.96,
    "Parabolic Dish": 124.22,
    "Phosphate and Sulfate Salts": 0.2999,
    "Phosphoric Acid": 0.13,
    "Photoresist Epoxy": 1,
    "Photovoltaic Panel": 6.75,
    "Platinum": 795,
    "Polyacrylonitrile": 0.247,
    "Polyacrylonitrile Fabric": 0.8,
    "Polymer Tantalum Capacitor": 90.69,
    "Polypropylene": 0.0173,
    "Potassium Carbonate": 0.09,
    "Potassium Chloride": 0.03,
    "Potassium Fluoride": 25,
    "Potassium Heptafluorotantalate": 7.89183,
    "Potassium Hydroxide": 0.09,
    "Potatoes": 0.2,
    "Power Module": 3000,
    "Pressure Vessel": 8329.86,
    "Propellant Tank": 14900,
    "Propulsion Module": 333361.11111111107,
    "Propylene": 0.03,
    "Pump": 79,
    "Pure Nitrogen": 0.0895,
    "Pyroxene": 0.091362,
    "Quicklime": 0.00085,
    "Radio Antenna": 129.032,
    "Rare Earth Oxides": 0.494812,
    "Rare Earth Sulfates": 0.115,
    "Raw Salts": 0.017,
    "Reactor Plumbing Assembly": 42522.5,
    "Refinery": 78152.1,
    "Rhabdite": 0.0725,
    "Rhabdite Slag": 0.738593,
    "Roasted Rhabdite": 0.115,
    "Robotic Arm": 205.375,
    "Shipyard": 286310,
    "Shuttle": 440388,
    "Shuttle Hull": 269420,
    "Silica": 0.18,
    "Silica Powder": 0.169,
    "Silicon": 2.8,
    "Silicon Wafer": 4,
    "Silver": 120,
    "Small Propellant Tank": 30,
    "Sodium Bicarbonate": 0.169,
    "Sodium Carbonate": 0.149,
    "Sodium Chloride": 0.014,
    "Sodium Chromate": 0.165878,
    "Sodium Dichromate": 0.471448,
    "Sodium Hydroxide": 0.028,
    "Sodium Tungstate": 0.54862,
    "Soil": 0.0105,
    "Solder": 8,
    "Solids Automation Module": 4400,
    "Soybeans": 0.277067,
    "Spaceport": 759821,
    "Spirulina and Chlorella Algae": 0.475,
    "Stainless Steel": 0.6,
    "Stainless Steel Pipe": 0.6,
    "Stainless Steel Sheet": 1.5,
    "Star Tracker": 66.1927,
    "Steel": 0.3,
    "Steel Beam": 0.1199,
    "Steel Cable": 0.1524,
    "Steel Pipe": 0.13,
    "Steel Sheet": 0.1299,
    "Steel Truss": 179.53125,
    "Steel Wire": 0.059228,
    "Sulfur": 0.156757,
    "Sulfur Dioxide": 0.178529,
    "Sulfuric Acid": 0.138,
    "Surface Mount Device Reel": 850,
    "Taenite": 0.072571,
    "Tantalum": 59.9,
    "Terrain Interface Module": 4999,
    "Thermal Module": 1640,
    "Thin-film Resistor": 5,
    "Tin": 3.95,
    "Tin Sulfide": 3.9,
    "Triple Superphosphate": 0.045,
    "Troilite": 0.091362,
    "Tungsten": 3.2,
    "Tungsten Powder": 4.35,
    "Turbopump": 15000,
    "Unenriched Uranium Hexafluoride": 2.45822,
    "Uraninite": 0.1,
    "Uranium Dioxide": 0.112075,
    "Uranium Tetrafluoride": 1.64292,
    "Uranyl Nitrate": 0.071403,
    "Warehouse": 33182.4,
    "Water": 0.0013577981651376146,
    "Weathered Olivine": 0.045,
    "Xenotime": 0.022949,
    "Yellowcake": 0.3,
    "Yttria": 20,
    "Zinc": 2.2068175331631914,
    "Zinc Oxide": 0.55
};

// Tools snapshot @ 2024-08-25
const toolsDefault = [
    {
        category_short: 'Mining',
        category: 'Mining Tools',
        items: [
            {title: 'Raw Materials', author: 'Elerium115', url: 'https://influence.elerium.dev/'},
            // {title: 'Materials Ratios', author: 'Elerium115', url: 'https://influence.elerium.dev/ratios.html'}, // misleading unless reworked
        ],
    },
    {
        category_short: 'Production',
        category: 'Production Tools',
        items: [
            {title: 'Products', author: 'Elerium115', url: 'https://influence.elerium.dev/products.html'},
            {title: 'Derived Products', author: 'Elerium115', url: 'https://influence.elerium.dev/derived-products.html'},
            {title: 'Production Planner', author: 'Elerium115', url: 'https://influence.elerium.dev/production-planner.html'},
            // {title: 'Production Chains', author: 'Elerium115', url: 'https://influence.elerium.dev/production.html'}, // to be reworked
            {title: 'Process Finder', author: 'Denker', url: 'https://www.adalia.info/tools/process-finder'},
            {title: 'Production Tracker', author: 'Denker', url: 'https://www.adalia.info/tools/production-tracker'},
            {title: 'Public Buildings', author: 'Denker', url: 'https://www.adalia.info/tools/public-buildings'},
            // {title: 'Product List', author: 'Daharius', url: 'https://influence.daharius.com/ProductList'}, // removed as requested by Daharius @ 2024-03-19
        ],
    },
    {
        category_short: 'Asteroids',
        category: 'Asteroids Tools',
        items: [
            {title: 'Asteroids Planner', author: 'Elerium115', url: 'https://influence.elerium.dev/asteroids-planner.html'},
            {title: 'Asteroid Management', author: 'Tyrell-Yutani', url: 'https://tyrell-yutani.app/#/asteroid'},
            {title: 'Asteroid Tracker & Visualizer', author: 'Daharius', url: 'https://influence.daharius.com/AsteroidsTracker'},
            {title: 'Asteroid Distances', author: 'Denker', url: 'https://www.adalia.info/tools/asteroid-distances'},
            {title: 'Asteroid Metadata Lookup by Daharius', author: 'Daharius', url: 'https://influence.daharius.com/AsteroidMetadata/1'},
            {title: 'Asteroid Metadata Lookup by trevis', author: 'trevis & Dirac', url: 'https://starksight.plus/collection/INFA/1'},
            {title: 'Lot Management', author: 'Denker', url: 'https://www.floodgate.space/tools/lot-management'},
            {title: 'Expiring Lots', author: 'Denker', url: 'https://www.adalia.info/tools/expiring-lots'},
            {title: 'SLY’s Influence', author: '[SLY] Shadow Loyal', url: 'https://github.com/ImGroovin/SLYs-Influence/'}, // blocked in iframe
            // {title: 'Adalia Co-orbital Rocks', author: 'RGR', url: 'https://adalia.coorbital.rocks/'}, // offline
        ],
    },
    {
        category_short: 'Crew',
        category: 'Crew Tools',
        items: [
            {title: 'Crew Tracker', author: 'Denker', url: 'https://www.adalia.info/tools/crew-tracker'},
            {title: 'Crew Member Services', author: 'Tyrell-Yutani', url: 'https://tyrell-yutani.app/#/crew'},
            {title: 'Adalian Crew Simulator', author: 'jpmti2016', url: 'https://influence-crew-builder.vercel.app/'},
            {title: 'Crewmate Metadata Lookup by Daharius', author: 'Daharius', url: 'https://influence.daharius.com/CrewmateMetadata/1'},
            {title: 'Crewmate Metadata Lookup by trevis', author: 'trevis & Dirac', url: 'https://starksight.plus/collection/INFC/1'},
            // {title: 'Crew Planner', author: 'Daharius', url: 'https://influence.daharius.com/CrewPlanner'}, // removed as requested by Daharius @ 2024-03-19
            {title: 'Crew Builder', author: 'Grey Area', url: 'https://adalia.academy/POC/index.html'},
            {title: 'Floodgate (hire crews)', author: 'Cheveuxxx & Denker', url: 'https://www.floodgate.space/'},
            {title: 'Crewmate Trait & Affinity Bonuses', author: '[official]', url: 'https://wiki.influenceth.io/en/gameplay/crewmates/bonuses'},
            {title: 'Action Planner (prototype)', author: 'Elerium115', url: 'https://elerium-115.github.io/influence-css/tool-action-planner/'},
        ],
    },
    {
        category_short: 'Flight',
        category: 'Flight Tools',
        items: [
            {title: 'System Travels Summary', author: 'trevis & Dirac', url: 'https://starksight.plus/flights'},
            {title: 'Flight Chart Zoom (Chrome)', author: 'RGR', url: 'https://chromewebstore.google.com/detail/influence-flight-chart-zo/makjdbggcjkjclglokiopecpghgmkgba'},
            {title: 'Flight Chart Zoom (Firefox)', author: 'RGR', url: 'https://addons.mozilla.org/en-US/firefox/addon/influence-flight-zoom-chart/'},
        ],
    },
    {
        category_short: 'Trading',
        category: 'Trading Tools',
        items: [
            {title: 'Trader Dashboard', author: 'Denker', url: 'https://www.adalia.info/tools/trader-dashboard'},
            {title: 'Marketplace Trades Summary', author: 'trevis & Dirac', url: 'https://starksight.plus/trades'},
            {title: 'Resource Prices', author: 'trevis & Dirac', url: 'https://starksight.plus/trades/129/price'},
            {title: 'Ships For Sale', author: 'Denker', url: 'https://www.adalia.info/tools/ships-for-sale'},
        ],
    },
    {
        category_short: 'Information',
        category: 'Information Tools',
        items: [
            {title: 'Influence Wiki', author: '[official]', url: 'https://wiki.influenceth.io/'}, // blocked in iframe
            // {title: 'Wendash', author: 'Joosh & Admiral', url: 'https://influence.wendash.com/'}, // password gated
            {title: 'Adalia Academy', author: 'Grey Area & Skippy', url: 'https://adalia.academy/'},
            // {title: 'Influence Sales', author: 'Teandy', url: 'https://influence-sales.space/'}, // offline
            {title: 'Adalia.Guide', author: 'Korivak', url: 'https://adalia.guide/'},
            {title: 'Adalia Info', author: 'Denker', url: 'https://adalia.info/'},
            {title: 'StarkSight Topics', author: '[community]', url: 'https://starksight.plus/topics'},
            {title: 'Analytics on Dune (Starknet)', author: 'brakmaar', url: 'https://dune.com/brakmaar/influence-game-data'}, // blocked in iframe
            {title: 'Analytics on Dune (L1)', author: 'brakmaar', url: 'https://dune.com/brakmaar/Influence-asteroids'}, // blocked in iframe
            // {title: 'Adalia.id', author: 'strwrsfrk & Myrhea', url: 'https://my.adalia.id/'}, // abandoned?
        ],
    },
    {
        category_short: 'Lore',
        category: 'Influence Lore',
        items: [
            {title: 'Last Night in Space', author: 'Korivak', url: 'https://lastnight.space/'},
            {title: 'Influence Lore by Korivak', author: 'Korivak', url: 'https://matthew.debarth.com/influence'}, // individual articles blocked in iframe
            {title: 'Influence Lore by strwrsfrk', author: 'strwrsfrk', url: 'https://strwrsfrk.medium.com/'}, // blocked in iframe
            {title: 'The Letters of Asterion South', author: 'Asterion South', url: 'https://asterionsouth.substack.com/'}, // blocked in iframe
        ],
    },
    {
        category_short: 'Games',
        category: 'Games',
        items: [
            {title: 'Influent', author: 'brakmaar', url: 'https://influent.vercel.app/'},
        ],
    },
];

// Widgets snapshot @ 2024-08-25
const widgetsDefault = [
    {title: 'Shopping List', url: 'https://influence.elerium.dev/widgets/shopping-list.html', default: true},
    {title: 'Marketplace Prices', url: 'https://widgets.starkgames.io/prices/129'},
    {title: 'Private Labels', url: 'https://influence.elerium.dev/widgets/private-labels.html'},
    {title: 'More coming soon...', url: null},
];
